applications:
  - name: transcription-service
    route_prefix: "/"
    import_path: src.deployments.ray_serve_models:app
    runtime_env: {}
    args:
      model_cache_path: "/app/models"
      default_whisper_model: "base"
      enable_diarization: true
      whisper_model: "base"
    deployments:
      - name: FastAPIIngress
        num_replicas: 1

http_options:
  host: "0.0.0.0"
  port: 8000
  root_path: ""

grpc_options:
  enable_grpc_logs: false